### ISSUE TITLE
Please make climb 6 frames long

### ISSUE THREAD

**Issue by bztsrc** [ElizaWy/LPC#2]
Dear Eliza,

Would it be possible to expand the climb animation to 6 frames? (Currently all the other LPC animations have at least 6 frames.)

I'm suggesting something like this (please forgive the quality, I'm not a pixel artist. The point is, I've added an extra frame and mirrored it).
![Climb](https://user-images.githubusercontent.com/12779069/168871020-4cd2e69e-ada8-4827-9ab0-74be83ac267b.gif)
Keep up the good work! I can hardly wait to see the missing animations! For now, I'm using classic LPC, but I'm eager to replace those with your LPC Revised.

Thanks,
bzt

**Comment by ElizaWy** [comment]
I suppose the question becomes, does it need to be smoother, or are you wanting more frames to match the others?

Right now, this is how the current 4-frame animation plays. It _is_ a bit choppy, but I'm still undecided.

![Ladder Climb Preview 2](https://user-images.githubusercontent.com/12552840/169064254-0ac8948b-ea4b-4040-ad46-06237024a2fa.gif) 
![Ladder Climb Preview 1](https://user-images.githubusercontent.com/12552840/169064744-a81ccbe4-3fca-42c9-9cbd-8c9aa07ac296.gif)

**Comment by bztsrc** [comment]
> I suppose the question becomes, does it need to be smoother, or are you wanting more frames to match the others?

Both. It would be great to have it smoother, and also matching a minimum number of frames of the others would be awesome.

I haven't changed much on your original anim, I've kept the arms/legs fully up/down and in the middle frames, and just added one extra frame in between, which is then mirrored. (Of course I've copied the hands and legs one frame further to make it match the movement; I believe that's the part what I messed up, and that's why my anim is "shaking" and looking poor. or maybe I should have moved the mirrored frame one pixel to the left?)

Anyway, that was just an example, you don't have to use my anim per se, I wanted to demonstrate (for myself as much as for you) how much difference just one additional frame can make. But if you can use it, feel free to do so, you don't have to credit me or anything (all body parts are your work anyway, I've just copy'n'pasted them).

Thanks,
bzt

ps: the arms and legs in the new frame were copied from the "jump" and "run" animations, I haven't drew them, that's your work too.

**Comment by bztsrc** [comment]
Ok, I've tried to fix it, I hope it is much more convincing now (but I'm still no pixel artist).
![Climb](https://user-images.githubusercontent.com/12779069/169968341-51e68332-67e4-4fae-b03f-95a631e755e0.gif)

Cheers,
bzt

**Comment by ElizaWy** [comment]
Thanks for that, Bzt!

I'll give it some tests and see what I can do. The Climb animation will be officially released with the mountain pack.

**Comment by bztsrc** [comment]
> Thanks for that, Bzt!

It was nothing, you did all the hard work.

> I'll give it some tests and see what I can do. The Climb animation will be officially released with the mountain pack.

Awesomesouce! Thank you very very much!

Currently I'm using the classic LPC, but I'm looking forward to replace that with your LPC Revised set!

bzt

**Comment by ElizaWy** [comment]
Hey, just a quick preview! I'll be releasing this with the big terrain pack. A six-frame climb.

![Cliff Climb Demo](https://user-images.githubusercontent.com/12552840/185069762-cd1b7c71-ecb3-4a74-97d5-4aee02d35f4a.gif)

**Comment by bztsrc** [comment]
That's pretty cool looking, thank you very much! I see you have fixed the upper arm and the feet, the animation looks just amazing!

Cheers,
bzt
