### ISSUE TITLE
Accessing it

### ISSUE THREAD

**Issue by mickperez101** [ElizaWy/LPC#3]
How do you access the LPC generator once you get the github link, and which software is used ? (Visual Studio, Visual Studio Code, etc)

**Comment by ElizaWy** [comment]
Do you mean the character creator? I don't have one myself, but Sander Frenken was kind enough to make one, which can be found here: https://sanderfrenken.github.io/lpc-spritesheet-generator-v2/#?body=Thin_brown&head=Masculine_brown

**Comment by mickperez101** [comment]
Yes I have that one which I do appreciate the help! But I met like I wanted to get the idle animation and then put my skin on it but I am having trouble to do so. Is there way to put it inside the generator? Is there anyway to add pre created lpc sprite to the generator so I can use that skin to get the idle animation etc. Or an update generator with attack animations as well.

**Comment by ElizaWy** [comment]
Well, if you'd like to make a custom edit, you'll need to download the .png files, and combine them in an image editor with your own art.
