### ISSUE TITLE
Incompatible with LPC Universal Sprite Sheets

### ISSUE THREAD

**Issue by btarg** [ElizaWy/LPC#4]
I would really appreciate having an updated version of the site at https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator, but using the LPC Revised characters, since there are already existing Unity plugins to use this type of character. Thanks!

**Comment by ElizaWy** [comment]
There is, actually!

https://sanderfrenken.github.io/lpc-spritesheet-generator-v2/#?body=Thin_brown&head=Masculine_brown

It's not the same layout, and I'm lacking my updates to the combat poses as of yet, but a bit of tweaking in Unity should get it running.
