### ISSUE TITLE
FYI: opengameart abused attributions

### ISSUE THREAD

**Issue by bztsrc** [ElizaWy/LPC#6]
Hi,

Just a heads up, MedicineStorm modified your commission's attribution without your consent.

https://opengameart.org/content/lpc-revised-elders

I've used both spritesets (LPC and yours), and your clothes are totally different and incompatible with the original, so I'm pretty sure you weren't using BenCreating's nor Redshrike's clothing, all your clothes are original and genuine (and much better than the original, may I add, only if there were some fantasy style armors).

Therefore I don't think it's okay to credit them for something that's entirely your work. Just to let you know.

Cheers,
bzt

**Comment by ElizaWy** [comment]
It's actually correct-- MedicineStorm and I discussed this privately. :)

The clothing is completely different than what I originally made for the jump animation, this is true-- _but_ the current clothing does use elements of the original animation's character base, and we wanted to be thorough. It's all good!

**Comment by bztsrc** [comment]
I see. In this case your credits.txt file is incorrect.
https://github.com/ElizaWy/LPC/blob/main/Characters%2C%20Adults/Clothing/Credits.txt

Cheers,
bzt

**Comment by ElizaWy** [comment]
Sorry for the delay! I caught Covid right around that time and forgot to reply.

You are correct, and that credit file has been updated. :) Cheers!

**Comment by bztsrc** [comment]
No worries! Hope you feel better now! I got Covid too (despite I already got two vaccination at that time), it's no joke.

Thanks again for this wonderful, very well designed and standardized, guidelined sprites!

Cheers,
bzt
