### ISSUE TITLE
Possibly write on the side what each animation means

### ISSUE THREAD

**Issue by bsl3** [ElizaWy/LPC#7]
Hey this is an amazing tool!
I was wondering if you could write on the website or something on what every animation on the sheet means.
for example the add "front walk" for the animation that is front walking
It can be a little hard to tell to make sure what everything does
thank you!

**Comment by ElizaWy** [comment]
I've actually done better!

Take a look at the Characters > _ Guides & Palettes > Animation Guide folder. Each animation is demonstrated, with suggested timing. They'll look like this:

![Walk - 30 FPS](https://github.com/ElizaWy/LPC/assets/12552840/990acd08-98f5-4be5-9dd4-25c7e3312d23)
