### ISSUE TITLE
[REQUEST] Script for generating spritesheets with weapons.

### ISSUE THREAD

**Issue by lazarovziv** [ElizaWy/LPC#8]
I don't know exactly where to ask, but I also wanted to say that your work is very good!
Anyway, I've noticed the spritesheets for weapons and for the bodies aren't compatible. How can I add a weapon to a body Spritesheet?
Thanks!

**Comment by lazarovziv** [comment]
Also, I don't understand why the head isn't shown on the body spritesheets :)

**Comment by ElizaWy** [comment]
Thank you! I appreciate it!

The weapons need more room than the character sheets allow for. With the ordinary character sheet, each square is 64x64 pixels. The weapon sheets and anything 'oversized' has to add more space, so they're using 128x128 squares, and fit right overtop the 64px character square with 32px of buffer all around. It doesn't stack in a graphics editor, but it should work seamlessly in a game engine.

The heads are disconnected so you can mix and match-- feminine heads on masculine bodies, elderly heads on whatever body you like, cutscene animations where the character can turn their head back and forth, or use the facial expressions.

**Comment by lazarovziv** [comment]
didn't quiet understand how to overlay the weapons image on top of the body image. I've tried overlaying the head images on top of the body images and it worked flawlessly, but with the weapons it didn't. Sorry to bother you it's just would be super cool if I'll be able to use your images!! Thanks for replying.
