### ISSUE TITLE
Clothes for Children.

### ISSUE THREAD

**Issue by goofytroll** [ElizaWy/LPC#9]
Are there any clothes for the children?  I cannot find any in here.  I love the asset, I am going to use it to prototype my game, if not in game.

**Comment by ElizaWy** [comment]
Children's clothing is something I'm currently working on!

In the meantime, some substitute clothing can be found [here](https://opengameart.org/content/lpc-clothes-for-children). They don't use standard hemlines, but they'd be a workable placeholder.
